# Generated by Django 4.2.1 on 2023-05-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatares'),
        ),
    ]
